schema_version: 1

context:
  version: "1.2.0"

package:
  name: cdislogging
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/cdislogging/cdislogging-${{ version }}.tar.gz
  sha256: ca7511b685bbf0b4727fef85ca4eab78271b4618139a621b09c2846aed6d19d1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python =${{ python_min }}
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - cdislogging
  - requirements:
      run:
        - pip
        - python =${{ python_min }}
    script:
      - pip check

about:
  summary: Standardized logging tool and format for cdis applications
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  homepage: https://github.com/uc-cdis/cdislogging

extra:
  recipe-maintainers:
    - danielnachun
